name: Check the working of Hashtag Generator

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  

    - name: Install pytorch
      run: pip3 install torch

    - name: Install Hugging face dependencies
      run: pip install transformers datasets

    - name: Install Flask
      run: pip install flask flask-cors pillow

    - name: Run flask app 
      run: python main.py