name: Check the working of Hashtag Generator

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.7'  

    - name: Create an env
      run: python -m venv venv
    
    - name: activate venv
      run: venv\Scripts\activate
    
    - name: Build Docker Image
      run: docker image build -t docker-flask-test .
    - name: Run Container
      run: docker run -p 5000:5000 -d docker-flask-test
    
    - name: Run test
      run: python test.py